name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
      id-token: write
      contents: read  

jobs: 
  terraform: 
    name: Terraform
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        id: fmt
        name: "Terraform Format"
        run: "terraform fmt -check"
        continue-on-error: true
      - 
        id: init
        name: "Terraform Init"
        run: "terraform init"
      - 
        id: validate
        name: "Terraform Validate"
        run: "terraform validate -no-color"
      - 
        id: plan
        if: "github.event_name == 'pull_request'"
        name: "Terraform Plan"
        run: "terraform plan -no-color"
        continue-on-error: true
      - 
        if: "steps.plan.outcome == 'failure'"
        name: "Terraform Plan Status"
        run: "exit 1"
        
      - 
        name: "configure aws credentials"
        uses: "aws-actions/configure-aws-credentials@v1"
        with:
          role-to-assume: "${{ secrets.ARN_SECRETS }}"
          role-session-name: "samplerolesession"
          aws-region: "me-south-1"

      - 
        if: "github.ref == 'refs/heads/main' && github.event_name == 'push'"
        name: "Terraform Apply"
        run: "terraform apply -auto-approve"
      
